### ISSUE TITLE
Docker Image Build Error with Node v10

### ISSUE THREAD

**Issue by liuderchi** [liuderchi/jupyter-nodejs#1]
When doing `docker build` in play-with-docker environment with **Node v10**,

it fails at `npm install` 

  of `Step 13/18 : RUN npm install && node install.js`

---

<details>
  <summary><em>build error log <code>Step 13/18 : RUN npm install && node install.js</code></em></summary>

```sh
Step 13/18 : RUN npm install && node install.js
 ---> Running in 166318a27141
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> zmq@2.15.3 install /usr/lib/jupyter-nodejs/node_modules/zmq
> node-gyp rebuild

make: Entering directory '/usr/lib/jupyter-nodejs/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
In file included from ../binding.cc:29:0:
/usr/include/zmq_utils.h:44:98: note: #pragma message: Warning: zmq_utils.h is deprecated. All its functionality is provided by zmq.h.
 #pragma message("Warning: zmq_utils.h is deprecated. All its functionality is provided by zmq.h.")
                                                                                                  ^
In file included from ../node_modules/nan/nan.h:190:0,
                 from ../binding.cc:38:
../node_modules/nan/nan_maybe_43_inl.h: In function 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)':
../node_modules/nan/nan_maybe_43_inl.h:88:15: error: 'class v8::Object' has no member named 'ForceSet'
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
               ^~~~~~~~
In file included from ../binding.cc:38:0:
../node_modules/nan/nan.h: In function 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)':
../node_modules/nan/nan.h:817:60: warning: 'v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, func, argc, argv);
                                                            ^
In file included from ../binding.cc:25:0:
/root/.node-gyp/10.7.0/include/node/node.h:172:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/root/.node-gyp/10.7.0/include/node/node.h:88:42: note: in definition of macro 'NODE_DEPRECATED'
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../binding.cc:38:0:
../node_modules/nan/nan.h: In function 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)':
../node_modules/nan/nan.h:831:62: warning: 'v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
                                                              ^
In file included from ../binding.cc:25:0:
/root/.node-gyp/10.7.0/include/node/node.h:165:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/root/.node-gyp/10.7.0/include/node/node.h:88:42: note: in definition of macro 'NODE_DEPRECATED'
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../binding.cc:38:0:
../node_modules/nan/nan.h: In function 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)':
../node_modules/nan/nan.h:845:62: warning: 'v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)'is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, method, argc, argv);
                                                              ^
In file included from ../binding.cc:25:0:
/root/.node-gyp/10.7.0/include/node/node.h:158:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/root/.node-gyp/10.7.0/include/node/node.h:88:42: note: in definition of macro 'NODE_DEPRECATED'
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../binding.cc:38:0:
../node_modules/nan/nan.h: In member function 'v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const':
../node_modules/nan/nan.h:1463:5: warning: 'v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     ));
     ^
In file included from ../binding.cc:25:0:
/root/.node-gyp/10.7.0/include/node/node.h:172:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/root/.node-gyp/10.7.0/include/node/node.h:88:42: note: in definition of macro 'NODE_DEPRECATED'
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
../binding.cc: In destructor 'zmq::Socket::IncomingMessage::MessageReference::~MessageReference()':
../binding.cc:999:54: warning: throw will always call terminate() [-Wterminate]
               throw std::runtime_error(ErrorMessage());
                                                      ^
../binding.cc:999:54: note: in C++11 destructors default to noexcept
../binding.cc: In destructor 'zmq::Socket::OutgoingMessage::~OutgoingMessage()':
../binding.cc:1205:50: warning: throw will always call terminate() [-Wterminate]
           throw std::runtime_error(ErrorMessage());
                                                  ^
../binding.cc:1205:50: note: in C++11 destructors default to noexcept
zmq.target.mk:95: recipe for target 'Release/obj.target/zmq/binding.o' failed
make: Leaving directory '/usr/lib/jupyter-nodejs/node_modules/zmq/build'
make: *** [Release/obj.target/zmq/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.4.0-96-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/jupyter-nodejs/node_modules/zmq
gyp ERR! node -v v10.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN The package mkdirp is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zmq@2.15.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-30T05_44_04_189Z-debug.log
The command '/bin/sh -c npm install && node install.js' returned a non-zero code: 1
```

</details>

---

Related [Dockerfile link](https://github.com/liuderchi/jupyter-nodejs/blob/docker/stable-slim-node9/Dockerfile#L8)

**Comment by liuderchi** [comment]
NOTE: zmq npm package Official installation guide

https://github.com/JustinTulloss/zeromq.node#installing-on-unixposix-and-osx
